<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-30T17:05:51 IST" name="Default suite" finished-at="2021-10-30T17:06:14 IST" duration-ms="23592">
    <groups>
    </groups>
    <test started-at="2021-10-30T17:05:51 IST" name="Default test" finished-at="2021-10-30T17:06:14 IST" duration-ms="23592">
      <class name="script">
        <test-method is-config="true" signature="setup()[pri:0, instance:script@7f1302d6]" started-at="2021-10-30T17:05:51 IST" name="setup" finished-at="2021-10-30T17:06:01 IST" duration-ms="10569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testNoWarning()[pri:0, instance:script@7f1302d6]" started-at="2021-10-30T17:06:01 IST" name="testNoWarning" finished-at="2021-10-30T17:06:04 IST" duration-ms="2320" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at script.testNoWarning(script.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNoWarning -->
        <test-method signature="testTitle()[pri:0, instance:script@7f1302d6]" started-at="2021-10-30T17:06:04 IST" name="testTitle" finished-at="2021-10-30T17:06:04 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method signature="testWarning()[pri:0, instance:script@7f1302d6]" started-at="2021-10-30T17:06:04 IST" name="testWarning" finished-at="2021-10-30T17:06:05 IST" duration-ms="1351" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWarning -->
        <test-method signature="testnothing()[pri:0, instance:script@7f1302d6]" started-at="2021-10-30T17:06:05 IST" name="testnothing" finished-at="2021-10-30T17:06:08 IST" duration-ms="3382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testnothing -->
        <test-method is-config="true" signature="clearUp()[pri:0, instance:script@7f1302d6]" started-at="2021-10-30T17:06:08 IST" name="clearUp" finished-at="2021-10-30T17:06:14 IST" duration-ms="5869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearUp -->
      </class> <!-- script -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
